<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        $id = $this->route('category');
        return [

                'name' => [
                    'required',
                    'min:3',
                    'max:255',
                    Rule::unique('categories' ,'name')->ignore($id),
//                    function($attribute , $value , $fails){
//                        if($value == 'usman'){
//                            $fails('fuck you');
//                        }
//                    }
//                    "|string|min:3|max:255|unique:categories,name,$id"
                ]
                    ,
                'parent_id' =>[
                    'int' , 'exists:categories,id' ,'nullable'
                ],
                'image'    =>[
                    'image','max:1048576','dimensions:min_width=150 , min_height=100'
                ],
                'status' => 'in:active,archived'

        ];
    }
    public function  messages()
    {
        return [
            'unique' => 'this filed :attribute must be unique another category have this name'
        ]; // TODO: Change the autogenerated stub
    }
}
